spring:
  redis:
    cache:
      # nodes: -127.0.0.1:7001
      #   -127.0.0.1:7002
      #   -127.0.0.1:7003
      #   -127.0.0.1:7004
      host: 10.8.16.78:6379
      password:
      maxIdle:
      minIdle:
      maxTotal:
      maxWaitMillis: 5000
    database: 0

dubbo:
  registry:
    protocol: zookeeper
    #公司zk
    address: 10.8.16.79:2181