server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: clife-dataplatform-upms-business
  datasource:
    name: dataplatform-quartz
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/dataplatform-quartz?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    cache:
      # nodes: -127.0.0.1:7001
      #   -127.0.0.1:7002
      #   -127.0.0.1:7003
      #   -127.0.0.1:7004
      host: 10.8.16.78:6379
      #host: 127.0.0.1:6379
      password:
      maxIdle:
      minIdle:
      maxTotal:
      maxWaitMillis: 5000
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #Mapper.xml所在的位置
  type-aliases-package: com.clife.dataplatform.upms.model
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: false

dubbo:
  registry:
    protocol: zookeeper
    #公司zk
    address: 10.8.16.79:2181
    #address: 127.0.0.1:2181
    id: lin-registry-1
  protocol:
    port: 12346
    name: dubbo
    id: dubbo
    status: server
  application:
    name: clife-dataplatform-business-upms-name
    id: clife-dataplatform-business-upms-id
    qos-enable: true
    qos-port: 22222
  scan:
    basePackages: com.clife.dataplatform.upms.service
hello:
  service:
    version: 1.0.0

logging:
  level:
    com.clife.dataplatform.upms.dao :  debug
